MAX_BETS:
  - 300
  - 350
  - 400
  - 450
  - 500
  - null
STARTING_BANKROLL: 1000
MIN_BET: 10
BET_INCREMENT: 10
NUM_DECKS: 4
DECK_PENETRATION: 0.8
NUM_PLAYERS: 3
NUM_SIMULATIONS_PER_COMBINATION: 1000
AGGRESSIVENESS_VALUES:
  - 0.0
  - 0.25
  - 0.5
  - 0.75
  - 1.0
SEE_OTHER_BETS_DURING_BETTING: True
